### ISSUE TITLE
pytest에서 post시 참조하는 외래키의 무결성 문제

### ISSUE THREAD

**Issue by Cloudblack** [Cloudblack/wanted_project_001_madup#18]
```@pytest.mark.django_db()
class Testview:  
    def test_db(self, client):
        response = client.post(
            reverse(views.get_create_ad),
            data={
                "user_id": "37445221",
                "media": "naver",
                "start_date": "2022-04-30",
                "end_date": "2022-05-30",
                "uid": "1819",
                "budget": "11.1",
                "estimated_spend": "51.1"
            }
        )
```
```1452, 'Cannot add or update a child row: a foreign key constraint fails ```

외래키가 참조하는 테이블에 기본키가 존재하지 않을 경우 발생 하는 에러인데

user_id는 존재하는 값이고 똑같은 값으로 post맨으로 동작시키면 멀쩡하게 동작합니다

**Comment by gshduet** [comment]
아. 문제가 뭔지 이해했습니다.
unit test의 경우 저희가 연결해 둔 db와 연동해서도 쓸 순 있지만 기본적으론 fake db에 연결했다고 가정하고 테스트를 돌리는 것으로 알고 있습니다. 그런 이유로 먼저 `def setUp` 을 통해 해당 아이디를 가진 유저를 만들어 둔 뒤 테스트를 진행해보는 것을 제안드립니다..!

**Comment by Cloudblack** [comment]
감사합니다 DB를 복사해와서 테스트하고 지우는거라고 잘못 생각하고있었습니다!!
